apiVersion: v1
kind: ServiceAccount
metadata:
  name: central
  namespace: {{.K8sConfig.Namespace}}
imagePullSecrets:
- name: stackrox
---
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  annotations:
    kubernetes.io/description: central is the security constraint for the central server
  name: central
priority: 100
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
users:
- system:serviceaccount:{{.K8sConfig.Namespace}}:central
volumes:
- '*'
{{if .HostPath -}}
allowHostDirVolumePlugin: true
{{- end}}
