apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: {{.Values.namespace}}
imagePullSecrets:
- name: stackrox
---
{{if eq .Values.clusterType "OPENSHIFT_CLUSTER"}}
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  annotations:
    kubernetes.io/description: monitoring is the security constraint for the monitoring stack
  name: monitoring
priority: 100
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
users:
- system:serviceaccount:{{.Values.namespace}}:monitoring
volumes:
- '*'
{{- end}}
