apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-certs
  namespace: stackrox
type: Opaque
stringData:
  server.crt: |-
    {{- .Files.Get "certs/tls.crt" | nindent 4 }}
  server.key: |-
    {{- .Files.Get "certs/tls.key" | nindent 4 }}
