gomod:
  mod-file: go.mod

yarn:
  lockfile: ui/yarn.lock
  node-modules-dirs:
    - ui/node_modules
    - ui/apps/platform/node_modules
    - ui/packages/tailwind-config/node_modules

patterns:
  - "*AUTHOR*"
  - "*COPYING*"
  - "*LICENSE*"
  - "*LICENCE*"
  - "*NOTICE*"
  - "*author*"
  - "*copying*"
  - "*license*"
  - "*License*"
  - "*notice*"
  - "package.json"
