apiVersion: v1
data:
  htpasswd: YWRtaW46JDJhJDA1JGRCY3NaRDRnU0NwQUxJcW44eDNSMWVEcGV6WWMwVVlVUGVKT0pNLlBtTEEvcUpjMXlOUC5PCjEtc2ltb246JDJhJDEyJG5lZjNxTnhrZjhpTy55WWVXRS81SHV3UkMydFE4MjJoTGhNZUhXdENlbUNnL3ozamxBWHp5CjIta3lsZTokMmEkMTIkbmVmM3FOeGtmOGlPLnlZZVdFLzVIdXdSQzJ0UTgyMmhMaE1lSFd0Q2VtQ2cvejNqbEFYenkK
kind: Secret
metadata:
  annotations:
    email: support@stackrox.com
    owner: stackrox
  labels:
    app.kubernetes.io/component: central
    app.kubernetes.io/instance: stackrox-central-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-central-services
  name: central-htpasswd
  namespace: stackrox
type: Opaque