# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

ignored = ["github.com/stackrox/rox","github.com/docker/docker/daemon"]
required = ["golang.org/x/tools/go/ast/astutil", "golang.org/x/tools/go/analysis", "golang.org/x/tools/go/analysis/passes/inspect", "golang.org/x/tools/go/ast/inspector"]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

# github.com/couchbase/moss has the incorrect version and doesn't run
[[override]]
  name = "github.com/couchbase/ghistogram"
  revision = "d910dd063dd68fb4d2a1ba344440f834ebb4ef62"

[[override]]
  name = "github.com/heroku/docker-registry-client"
  source = "github.com/stackrox/docker-registry-client.git"
  revision = "3d98b2b79d1baebfb4deee7df2658afdf12b9b58"

[[constraint]]
  name = "github.com/etcd-io/bbolt"
  version = "v1.3.2"

[[constraint]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "7c9e64a2e1891bf1020d9312a18741c734fa1cd6"
  [metadata]
  upstream = "17.09-ce plus additional commits to fix Darwin build"

[[constraint]]
  name = "github.com/docker/go-units"
  branch = "master"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  branch = "master"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "v1.5.1"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  branch = "master"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "=1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "google.golang.org/genproto"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.20.1"

[[constraint]]
  name = "gopkg.in/robfig/cron.v2"
  revision = "be2e0b0deed5a68ffee390b4583a13aff8321535"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "github.com/deckarep/golang-set"
  version = "v1.7"

[[constraint]]
  name = "github.com/andygrunwald/go-jira"
  version = "v1.0.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.1"

[[constraint]]
  name = "github.com/cloudflare/cfssl"
  branch = "master"

[[override]]
  name = "github.com/google/certificate-transparency-go"
  version = "v1.0.21"

[[constraint]]
  name = "github.com/NYTimes/gziphandler"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  version = "2.1.3"
  name = "gopkg.in/square/go-jose.v2"

[[constraint]]
  name = "github.com/coreos/clair"
  version = "v2.0.1"

[[constraint]]
  name = "github.com/blevesearch/bleve"
  source = "https://github.com/connorgorman/bleve.git"
  revision = "0afc050c685d17d4f46422632f40149d0aeed596"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.8.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"

  version = "v1.1"
[[constraint]]
  name = "github.com/openshift/api"
  version = "v3.9.0"

[[constraint]]
  name = "github.com/openshift/client-go"
  version = "v3.9.0"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "v1.2.0"

[[constraint]]
  name = "golang.org/x/time"
  branch = "master"

[[constraint]]
  name = "github.com/stackrox/clairify"
  revision = "52856608eab5d2703730450e3440d2765766e200"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.19.9"

[[constraint]]
  name = "github.com/tkuchiki/go-timezone"
  branch = "master"

[[constraint]]
  name = "github.com/golang/mock"
  version = "v1.1.1"

[[constraint]]
  name = "github.com/mauricelam/genny"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/graph-gophers/graphql-go"

[[constraint]]
  name = "k8s.io/helm"
  source = "https://github.com/helm/helm.git"
  version = "2.11.0"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "v2.0.0-rc.12"

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.34.0"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "v18"

[[constraint]]
  name = "github.com/mailru/easyjson"
  branch = "master"

[[constraint]]
  name = "github.com/dgraph-io/badger"
  revision = "28ef9bfd243809d6f4abc7dfa1ad92984eac9b66"

[[constraint]]
  name = "github.com/PagerDuty/go-pagerduty"
  revision = "fe8f9c4593d05f029afeb2c08c3e220120306506"

[[constraint]]
  name = "github.com/stackrox/anchore-client"
  revision = "608e0af2c0b40eeebf71c6c5d24f04de64510bf6"

[[constraint]]
  name = "github.com/fullsailor/pkcs7"
  source = "https://github.com/misberner/pkcs7.git"
  revision = "a48bf0f78dea7977a5bfcc5b0ffab3cbed62f01a"

[[constraint]]
  name = "github.com/mitchellh/hashstructure"
  revision = "a38c50148365edc8df43c1580c48fb2b3a1e9cd7"
