kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ivan-test-role
rules:
- apiGroups:
  - '*'
  resources:
  - "deployments"
  - "daemonsets"
  - "replicasets"
  - "configmaps"
  - "services"
  - "pods"
  - "pods/log"
  - "events"
  - "namespaces"
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ivan-test-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ivan-test-role
subjects:
- kind: ServiceAccount
  name: ivan-test
  namespace: default
