
version: {{.K8sConfig.MainImageTag}}

clusterType: {{.ClusterType.String}}

namespace: stackrox

image: {{.K8sConfig.Monitoring.Image}}

resources:
  requests:
    memory: "500Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

secrets:
  data:
    monitoring-ca.pem: {{index .SecretsBase64Map "ca.pem"}}
    monitoring-db-cert.pem: {{index .SecretsBase64Map "monitoring-db-cert.pem"}}
    monitoring-db-key.pem: {{index .SecretsBase64Map "monitoring-db-key.pem"}}
    monitoring-ui-cert.pem: {{index .SecretsBase64Map "monitoring-ui-cert.pem"}}
    monitoring-ui-key.pem: {{index .SecretsBase64Map "monitoring-ui-key.pem"}}
    monitoring-password: {{index .SecretsBase64Map "monitoring-password"}}

exposure:
  port: 443
  {{if eq .K8sConfig.Monitoring.LoadBalancerType.String "LOAD_BALANCER"}}
  type: LoadBalancer
  {{else if eq .K8sConfig.Monitoring.LoadBalancerType.String "NODE_PORT"}}
  type: NodePort
  {{else if eq .K8sConfig.Monitoring.LoadBalancerType.String "ROUTE"}}
  type: Route
  {{else}}
  type: None
  {{- end}}

persistence:
{{if eq .K8sConfig.Monitoring.PersistenceType.String "hostpath"}}
  name: monitoring-db
  type: hostpath
  value:
    hostPath:
      path: {{.K8sConfig.Monitoring.HostPath.HostPath}}
{{- else if eq .K8sConfig.Monitoring.PersistenceType.String "pvc"}}
  name: {{.K8sConfig.Monitoring.External.Name}}
  type: pv
  storageClass: {{.K8sConfig.Monitoring.External.StorageClass}}
  value:
    persistentVolumeClaim:
      claimName: {{.K8sConfig.Monitoring.External.Name}}
{{- else}}
  name: empty-db
  type: none
  value:
    emptyDir: {}
{{- end}}

{{if ne .K8sConfig.Monitoring.HostPath.NodeSelectorKey "" -}}
nodeSelector:
  {{.K8sConfig.Monitoring.HostPath.NodeSelectorKey}}: {{.K8sConfig.Monitoring.HostPath.NodeSelectorValue}}
{{end -}}
