spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: scanner
        resources:
          requests:
            memory: "1500Mi"
            cpu: "1000m"
          limits:
            memory: "2500Mi"
            cpu: "2000m"
