spec:
  template:
    spec:
      containers:
      - name: sensor
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"