{{if not .Values.gcpMarketplace}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: central
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: stackrox
imagePullSecrets:
- name: stackrox
{{end}}
---
{{if eq .Values.clusterType "OPENSHIFT_CLUSTER"}}
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  annotations:
    kubernetes.io/description: central is the security constraint for the central server
  name: central
  labels:
    app.kubernetes.io/name: stackrox
{{if eq .Values.persistence.type "hostpath" -}}
allowHostDirVolumePlugin: true
{{else}}
allowHostDirVolumePlugin: false
{{- end}}
allowedCapabilities: []
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
  ranges:
    - max: 4000
      min: 4000
priority: 100
readOnlyRootFilesystem: true
requiredDropCapabilities: []
runAsUser:
  type: MustRunAs
  uid: 4000
seLinuxContext:
  type: MustRunAs
seccompProfiles:
  - '*'
users:
- system:serviceaccount:{{.Values.namespace}}:central
volumes:
- '*'
{{- end}}
