{{if .Values.secrets.defaulttlscert }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: central-default-tls-cert
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: stackrox
{{if not .Values.gcpMarketplace}}
  annotations:
    "helm.sh/hook": "pre-install"
{{end}}
{{ toYaml .Values.secrets.defaulttlscert }}
{{end}}
