{{if .Values.secrets.defaulttlscert }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: central-default-tls-cert
  namespace: {{.Values.namespace}}
  annotations:
    "helm.sh/hook": "pre-install"
{{ toYaml .Values.secrets.defaulttlscert }}
{{end}}
