{{if .Values.secrets.htpasswd}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: central-htpasswd
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: stackrox
{{if not .Values.gcpMarketplace}}
  annotations:
    "helm.sh/hook": "pre-install"
{{end}}
{{toYaml .Values.secrets.htpasswd}}
{{end}}
