{{if .Values.secrets.htpasswd}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: central-htpasswd
  namespace: {{.Values.namespace}}
  annotations:
    "helm.sh/hook": "pre-install"
{{toYaml .Values.secrets.htpasswd}}
{{end}}