{{if eq .Values.exposure.type "Route"}}
apiVersion: v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: central
  name: central-mtls
  namespace: {{.Values.namespace}}
spec:
  host: central.stackrox
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: central
{{else if ne .Values.exposure.type "None"}}
apiVersion: v1
kind: Service
metadata:
  name: central-loadbalancer
  namespace: {{.Values.namespace}}
spec:
  ports:
  - port: {{.Values.exposure.port}}
    targetPort: 443
  selector:
    app: central
  type: {{.Values.exposure.type}}
{{- end}}
