apiVersion: v1
kind: ServiceAccount
metadata:
  name: central
  namespace: {{.Values.namespace}}
imagePullSecrets:
- name: stackrox
---
{{if eq .Values.clusterType "OPENSHIFT_CLUSTER"}}
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  annotations:
    kubernetes.io/description: central is the security constraint for the central server
  name: central
priority: 100
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
users:
- system:serviceaccount:{{.Values.namespace}}:central
volumes:
- '*'
{{if eq .Values.persistence.type "hostpath" -}}
allowHostDirVolumePlugin: true
{{- end}}
{{- end}}
