apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: central-tls
  namespace: {{.Values.namespace}}
{{if not .Values.gcpMarketplace}}
  annotations:
    "helm.sh/hook": "pre-install"
{{end}}
{{toYaml .Values.secrets.tls}}
