apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
imagePullSecrets:
- name: {{.Values.scannerSecretName}}
---
{{if eq .Values.clusterType "OPENSHIFT_CLUSTER"}}
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  annotations:
    kubernetes.io/description: security context constraint for scanner-v2
  name: scanner-v2
  labels:
    app.kubernetes.io/name: stackrox
priority: 100
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
users:
- system:serviceaccount:stackrox:scanner-v2
volumes:
- '*'
{{- end}}
