apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
imagePullSecrets:
- name: {{.Values.scannerSecretName}}

