apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: stackrox
  labels:
    app: {{ .Values.appName }}
    app.kubernetes.io/name: stackrox
spec:
  type: {{ .Values.anchoreApi.service.type }}
  ports:
    - name: http-anchore-external-api
      port: {{ .Values.anchoreApi.service.port }}
      targetPort: {{ .Values.anchoreApi.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.appName }}
