apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.dbAppName }}
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
spec:
  ingress:
  - from:
      - podSelector:
          matchLabels:
            app: {{ .Values.appName }}
    ports:
    - port: 5432
      protocol: TCP
  podSelector:
    matchLabels:
      app: {{ .Values.dbAppName }}
  policyTypes:
    - Ingress
