apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.appName }}
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
spec:
  ingress:
  - from:
      - podSelector:
          matchLabels:
            app: central
    ports:
    - port: 8228
      protocol: TCP
  podSelector:
    matchLabels:
      app: {{ .Values.appName }}
  policyTypes:
    - Ingress
