apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbAppName }}
  labels:
    app: {{ .Values.dbAppName }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
  - name: postgresql
    port: {{ .Values.postgresql.service.port }}
    targetPort: postgresql
  selector:
    app: {{ .Values.dbAppName }}
