apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbAppName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.dbAppName }}
    app.kubernetes.io/name: stackrox
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
  - name: postgresql
    port: {{ .Values.postgresql.service.port }}
    targetPort: postgresql
  selector:
    app: {{ .Values.dbAppName }}
