apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbAppName }}
  labels:
    app: {{ .Values.dbAppName }}
type: Opaque
data:
  postgres-password:  {{ .Values.postgresql.postgresPassword | b64enc | quote }}
