apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
type: Opaque
stringData:
  ANCHORE_ADMIN_PASSWORD: {{ .Values.anchoreGlobal.defaultAdminPassword | quote }}
  ANCHORE_DB_PASSWORD: {{ index .Values "postgresql" "postgresPassword" | quote }}
