generators:
- name: qa
  key:
    keyResourceId: "projects/stackrox-dev/locations/global/keyRings/licensing-qa/cryptoKeys/qa-license-signer/cryptoKeyVersions/1"
  limit:
    maxDuration: 1382400000000000
    allowOffline: true
    allowNoNodeLimit: true
    allowNoBuildFlavorRestriction: true
    deploymentEnvironments:
      - gcp/srox-temp-dev-test # Infra project
      - azure/66c57ff5-f49f-4510-ae04-e26d3ad2ee63
      - aws/051999192406  # setup-automation
      - aws/880732477823  # k@stackrox.com
      - aws/393282794030  # gavin@stackrox.com
- name: ci
  key:
    keyResourceId: "projects/stackrox-dev/locations/global/keyRings/licensing-ci/cryptoKeys/ci-license-signer/cryptoKeyVersions/1"
  limit:
    maxDuration: 21600000000000
    allowOffline: true
    maxNodeLimit: 10
    allowNoBuildFlavorRestriction: true
    deploymentEnvironments:
      - gcp/stackrox-ci
      - aws/051999192406
- name: dev
  key:
    keyResourceId: "projects/stackrox-dev/locations/us-west2/keyRings/licensing-dev/cryptoKeys/dev-license/cryptoKeyVersions/9"
  limit:
    maxDuration: 2592000000000000
    allowOffline: true
    maxNodeLimit: 50
    buildFlavors:
      - development
    allowNoDeploymentEnvironmentRestriction: true
- name: demo
  key:
    keyResourceId: "projects/stackrox-dev/locations/global/keyRings/licensing-demos/cryptoKeys/demo-license-signer/cryptoKeyVersions/1"
  limit:
    maxDuration: 2592000000000000
    allowOffline: true
    maxNodeLimit: 50
    allowNoBuildFlavorRestriction: true
    deploymentEnvironments:
      - gcp/srox-temp-sales-demos
      - azure/66c57ff5-f49f-4510-ae04-e26d3ad2ee63
      - aws/051999192406
datastore:
  project: stackrox-licensing
  namespace: internal
