apiVersion: v1
kind: Service
metadata:
  name: monitoring-lb
  namespace: stackrox
spec:
  ports:
  - name: chronograf
    port: 8888
    targetPort: 8888
  - name: influxdb
    port: 8086
    targetPort: 8086
  selector:
    app: monitoring
  type: LoadBalancer
