apiVersion: v1
kind: Service
metadata:
  name: monitoring-lb
  namespace: stackrox
spec:
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
  - name: influxdb
    port: 8086
    targetPort: 8086
  selector:
    app: monitoring
  type: LoadBalancer
