apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scanner
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: stackrox
    app: scanner
  annotations:
    owner: stackrox
    email: support@stackrox.com
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      namespace: {{.Values.namespace}}
      labels:
        app.kubernetes.io/name: stackrox
        app: scanner
    spec:
      {{if eq .Values.clusterType "OPENSHIFT_CLUSTER"}}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 25
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/compute
                    operator: In
                    values:
                    - "true"
            - weight: 75
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/infra
                    operator: NotIn
                    values:
                    - "true"
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: NotIn
                    values:
                    - "true"
      {{- end}}
      containers:
      - name: scanner
        image: {{.Values.image}}
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "2000Mi"
            cpu: "2000m"
        env:
        - name: CLAIR_ARGS
          value: "-insecure-tls"
        command:
        - /entrypoint.sh
        - /clairify
        imagePullPolicy: Always
        ports:
        - name: clairify
          containerPort: 8080
        securityContext:
          capabilities:
            drop: ["NET_RAW"]
        volumeMounts:
        - name: clair-config-volume
          mountPath: /etc/clair
          readOnly: true
        - name: scanner-tls-volume
          mountPath: /run/secrets/stackrox.io/certs/
          readOnly: true
        - name: proxy-config-volume
          mountPath: /run/secrets/stackrox.io/proxy-config/
          readOnly: true
      serviceAccount: scanner
      volumes:
      - name: clair-config-volume
        configMap:
          name: clair-config
      - name: scanner-tls-volume
        secret:
          secretName: scanner-tls
      - name: proxy-config-volume
        secret:
          secretName: proxy-config
          optional: true
