apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scanner
  namespace: {{.Values.namespace}}
  labels:
    app: scanner
  annotations:
    owner: stackrox
    email: support@stackrox.com
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      namespace: {{.Values.namespace}}
      labels:
        app: scanner
    spec:
      containers:
      - name: scanner
        image: {{.Values.image}}
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "2000Mi"
            cpu: "2000m"
        env:
        - name: CLAIR_ARGS
          value: "-insecure-tls"
        command:
        - /init
        - /clairify
        imagePullPolicy: Always
        ports:
        - name: clair
          containerPort: 6060
        - name: clairify
          containerPort: 8080
        securityContext:
          capabilities:
            drop: ["NET_RAW"]
        volumeMounts:
        - name: clair-config-volume
          mountPath: /etc/clair
          readOnly: true
      serviceAccount: scanner
      volumes:
      - name: clair-config-volume
        configMap:
          name: clair-config
