apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: scanner
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: stackrox
spec:
  ingress:
  - from:
      - podSelector:
          matchLabels:
            app: central
    ports:
    - port: 8080
      protocol: TCP
    - port: 8443
      protocol: TCP
  podSelector:
    matchLabels:
      app: scanner
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: scanner-db
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: stackrox
spec:
  ingress:
  - from:
      - podSelector:
          matchLabels:
            app: scanner
    ports:
    - port: 5432
      protocol: TCP
  podSelector:
    matchLabels:
      app: scanner-db
  policyTypes:
    - Ingress
