apiVersion: v1
kind: ServiceAccount
metadata:
  name: scanner
  namespace: {{.Values.namespace}}
imagePullSecrets:
- name: {{.Values.scannerSecretName}}
---
{{if eq .Values.clusterType "OPENSHIFT_CLUSTER"}}
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  annotations:
    kubernetes.io/description: scanner is the security constraint for the Scanner container
  name: scanner
priority: 100
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
users:
- system:serviceaccount:{{.Values.namespace}}:scanner
volumes:
- '*'
{{- end}}
