apiVersion: v1
kind: Service
metadata:
  name: scanner
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: stackrox
spec:
  ports:
  - name: http-clairify
    port: 8080
    targetPort: 8080
  selector:
    app: scanner
  type: ClusterIP
