apiVersion: v1
kind: Service
metadata:
  name: scanner
  namespace: {{.Values.namespace}}
spec:
  ports:
  - name: http-clair
    port: 6060
    targetPort: 6060
  - name: http-clairify
    port: 8080
    targetPort: 8080
  selector:
    app: scanner
  type: ClusterIP
