- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - scorecard-test
    - basic-check-spec
    image: scorecard-test:latest
    labels:
      suite: basic
      test: basic-check-spec-test
