apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensor
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
imagePullSecrets:
- name: stackrox
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: benchmark
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
imagePullSecrets:
- name: stackrox
---
{{if ne .CollectionMethod "NO_COLLECTION"}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
imagePullSecrets:
- name: stackrox
- name: stackrox-collector
---
{{- end}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: stackrox:monitor-deployments
  labels:
    app.kubernetes.io/name: stackrox
rules:
  - resources:
    - cronjobs
    - jobs
    - daemonsets
    - deployments
    - deploymentconfigs
    - namespaces
    - pods
    - replicasets
    - replicationcontrollers
    - services
    - statefulsets
    - secrets
    apiGroups:
    - '*'
    verbs:
    - get
    - watch
    - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: stackrox:monitor-deployments-binding
  labels:
    app.kubernetes.io/name: stackrox
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: stackrox:monitor-deployments
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: stackrox:enforce-policies
  labels:
    app.kubernetes.io/name: stackrox
rules:
  - resources:
    - cronjobs
    - jobs
    - daemonsets
    - deployments
    - deployments/scale
    - deploymentconfigs
    - pods
    - replicasets
    - replicationcontrollers
    - services
    - statefulsets
    apiGroups:
    - '*'
    verbs:
    - update
    - patch
    - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: stackrox:enforce-policies-binding
  labels:
    app.kubernetes.io/name: stackrox
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: stackrox:enforce-policies
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: stackrox:launch-benchmarks
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
rules:
  - resources:
    - daemonsets
    - deployments
    apiGroups:
    - extensions
    verbs:
    - create
    - get
    - delete
    - deletecollection
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: stackrox:launch-benchmarks-binding
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: Role
  name: stackrox:launch-benchmarks
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:network-policies
  labels:
    app.kubernetes.io/name: stackrox
rules:
  - resources:
    - networkpolicies
    apiGroups:
    - '*'
    verbs:
    - get
    - watch
    - list
    - create
    - update
    - patch
    - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:network-policies-binding
  labels:
    app.kubernetes.io/name: stackrox
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: stackrox:network-policies
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:view-nodes
  labels:
    app.kubernetes.io/name: stackrox
rules:
- resources:
  - nodes
  apiGroups: [""]
  verbs:
  - get
  - watch
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:view-nodes-binding
  labels:
    app.kubernetes.io/name: stackrox
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: stackrox:view-nodes
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:create-events
  labels:
    app.kubernetes.io/name: stackrox
rules:
- resources:
  - events
  apiGroups: [""]
  verbs:
  - create
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:create-events-binding
  labels:
    app.kubernetes.io/name: stackrox
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: stackrox:create-events
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:update-namespaces
  labels:
    app.kubernetes.io/name: stackrox
rules:
  - resources:
      - namespaces
    apiGroups: [""]
    verbs:
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:update-namespaces-binding
  labels:
    app.kubernetes.io/name: stackrox
subjects:
  - kind: ServiceAccount
    name: sensor
    namespace: stackrox
roleRef:
  kind: ClusterRole
  name: stackrox:update-namespaces
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:view-rbac
  labels:
    app.kubernetes.io/name: stackrox
rules:
  - resources:
      - roles
      - clusterroles
      - rolebindings
      - clusterrolebindings
      - serviceaccounts
    apiGroups:
      - ""
      - "rbac.authorization.k8s.io"
    verbs:
      - get
      - watch
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:view-rbac-binding
  labels:
    app.kubernetes.io/name: stackrox
subjects:
  - kind: ServiceAccount
    name: sensor
    namespace: stackrox
roleRef:
  kind: ClusterRole
  name: stackrox:view-rbac
  apiGroup: rbac.authorization.k8s.io
---
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  annotations:
    kubernetes.io/description: sensor is the security constraint for the sensor server
  name: sensor
  labels:
    app.kubernetes.io/name: stackrox
users:
- system:serviceaccount:stackrox:sensor
priority: 100
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  annotations:
    kubernetes.io/description: benchmark is the security constraint for the benchmark container
  name: benchmark
  labels:
    app.kubernetes.io/name: stackrox
users:
- system:serviceaccount:stackrox:benchmark
priority: 100
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
allowHostDirVolumePlugin: true
allowHostPID: true
volumes:
- '*'
---
{{if ne .CollectionMethod "NO_COLLECTION"}}
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  annotations:
    kubernetes.io/description: This SCC is based on privileged, hostaccess, and hostmount-anyuid
  name: collector
  labels:
    app.kubernetes.io/name: stackrox
users:
- system:serviceaccount:stackrox:collector
allowHostDirVolumePlugin: true
allowPrivilegedContainer: true
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: null
priority: 100
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
volumes:
- '*'
{{- end}}
