apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: stackrox
imagePullSecrets:
- name: stackrox
---
{{ if .Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints" }}
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  annotations:
    kubernetes.io/description: monitoring is the security constraint for the monitoring stack
  name: monitoring
  labels:
    app.kubernetes.io/name: stackrox
priority: 100
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
users:
- system:serviceaccount:{{ .Release.Namespace }}:monitoring
volumes:
- '*'
allowHostDirVolumePlugin: {{ eq .Values.persistence.type "hostpath" }}
allowedCapabilities: []
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
defaultAddCapabilities: []
readOnlyRootFilesystem: true
requiredDropCapabilities: []
{{- end}}
