apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: stackrox
{{ if not .Values.gcpMarketplace }}
  annotations:
    "helm.sh/hook": "pre-install"
{{ end }}
{{- $ca := genCA "StackRox Monitoring CA" 365 -}}
{{- $dbCert := genSignedCert "StackRox Monitoring DB" list (list (printf "monitoring-db.%s" .Release.Namespace)) 365 $ca -}}
{{- $uiCert := genSignedCert "StackRox Monitoring UI" list (list (printf "monitoring-ui.%s" .Release.Namespace)) 365 $ca -}}
stringData:
  monitoring-ca.pem: |
    {{- $ca.Cert | nindent 4 }}
  monitoring-db-cert.pem: |
    {{- $dbCert.Cert | nindent 4 }}
  monitoring-db-key.pem: |
    {{- $dbCert.Key | nindent 4 }}
  monitoring-ui-cert.pem: |
    {{- $uiCert.Cert | nindent 4 }}
  monitoring-ui-key.pem: |
    {{- $uiCert.Key | nindent 4 }}
  monitoring-password: {{ required "A password is required" .Values.password }}
