apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rhacs-operator-{{ .Release.Name }}
    control-plane: controller-manager
  name: rhacs-operator-controller-manager-{{ .Release.Name }}
  namespace: "{{ .Values.operator.targetNamespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhacs-operator-{{ .Release.Name }}
      control-plane: controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rhacs-operator-{{ .Release.Name }}
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=0
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
          imagePullPolicy: IfNotPresent
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          env:
            - name: ROX_OPERATOR_OUTER_MODE
              value: "{{.Values.operator.outerMode}}"
            - name: ENABLE_WEBHOOKS
              value: false
            - name: RELATED_IMAGE_MAIN
            - name: RELATED_IMAGE_SCANNER
            - name: RELATED_IMAGE_SCANNER_SLIM
            - name: RELATED_IMAGE_SCANNER_DB
            - name: RELATED_IMAGE_SCANNER_DB_SLIM
            - name: RELATED_IMAGE_COLLECTOR_SLIM
            - name: RELATED_IMAGE_COLLECTOR_FULL
            - name: RELATED_IMAGE_ROXCTL
            - name: RELATED_IMAGE_CENTRAL_DB
            - name: MEMORY_LIMIT_BYTES
              valueFrom:
                resourceFieldRef:
                  containerName: manager
                  resource: limits.memory
                  divisor: '0'
          image: quay.io/rhacs-eng/stackrox-operator:{{.Values.operator.version}}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 200m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: rhacs-operator-controller-manager-{{ .Release.Name }}
      serviceAccountName: rhacs-operator-controller-manager-{{ .Release.Name }}
      terminationGracePeriodSeconds: 10
