apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rhacs-operator-{{ .Release.Name }}
    control-plane: controller-manager
  name: rhacs-operator-manager-metrics-service-{{ .Release.Name }}
  namespace: rhacs-operator
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app: rhacs-operator-{{ .Release.Name }}
    control-plane: controller-manager
status:
  loadBalancer: {}
