---
# apiVersion: v1
# imagePullSecrets:
#   - name: quay-ips
# kind: ServiceAccount
# metadata:
#   name: rhacs-operator-controller-manager-stackrox-secured-cluster-services
#   namespace: "{{ .Values.operator.targetNamespace }}"
