apiVersion: v1
kind: Service
metadata:
  namespace: stackrox
  name: central-plaintext
spec:
  type: ClusterIP
  selector:
    app: central
  ports:
  - port: 80
    targetPort: 8080
    name: http-plain
  - port: 81
    targetPort: 8081
    name: grpc-plain
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-proxies-to-central-plaintext
  namespace: stackrox
spec:
  podSelector:
    matchLabels:
      app: central
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              stackrox-proxies: "true"
          podSelector:
            matchLabels:
              stackrox-proxies/central: "true"
      ports:
        - port: 8080
          protocol: TCP
        - port: 8081
          protocol: TCP
