kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: authorization-plugin
priority: 100
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: RunAsAny
seccompProfiles:
  - '*'
users:
  - system:serviceaccount:stackrox:authorization-plugin