# permissions for end users to edit authproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authprovider-editor-role
rules:
- apiGroups:
  - authprovider.central.stackrox.io
  resources:
  - authproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authprovider.central.stackrox.io
  resources:
  - authproviders/status
  verbs:
  - get
