apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: stackrox
  labels:
    app.kubernetes.io/name: stackrox
    auto-upgrade.stackrox.io/component: "sensor"
webhooks:
  - name: policyeval.stackrox.io
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - '*'
        operations:
          - CREATE
        resources:
          - pods
          - deployments
          - replicasets
          - replicationcontrollers
          - statefulsets
          - daemonsets
    namespaceSelector:
       matchExpressions:
       - key: namespace.metadata.stackrox.io/name
         operator: NotIn
         values:
         - stackrox
         - kube-system
         - kube-public
    failurePolicy: Ignore
    clientConfig:
      caBundle: {{.CABundle}}
      service:
        namespace: stackrox
        name: sensor-webhook
        path: /admissioncontroller
