apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: stackrox
webhooks:
  - name: policyeval.stackrox.io
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - '*'
        operations:
          - CREATE
        resources:
          - pods
          - deployments
          - replicasets
          - replicationcontrollers
          - statefulsets
          - daemonsets
    failurePolicy: Ignore
    clientConfig:
      caBundle: {{.CABundle}}
      service:
        namespace: {{.Namespace}}
        name: sensor
