apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensor
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
imagePullSecrets:
- name: stackrox
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: benchmark
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
imagePullSecrets:
- name: stackrox
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:monitor-deployments
  labels:
    app.kubernetes.io/name: stackrox
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:enforce-policies
  labels:
    app.kubernetes.io/name: stackrox
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: launch-benchmarks
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:network-policies
  labels:
    app.kubernetes.io/name: stackrox
rules:
  - resources:
    - 'networkpolicies'
    apiGroups:
    - '*'
    verbs:
    - get
    - watch
    - list
    - create
    - update
    - patch
    - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:network-policies-binding
  labels:
    app.kubernetes.io/name: stackrox
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: stackrox:network-policies
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:view-nodes
  labels:
    app.kubernetes.io/name: stackrox
rules:
- resources:
  - nodes
  apiGroups: [""]
  verbs:
  - get
  - watch
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:view-nodes-binding
  labels:
    app.kubernetes.io/name: stackrox
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: stackrox:view-nodes
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:update-namespaces
  labels:
    app.kubernetes.io/name: stackrox
rules:
- resources:
  - namespaces
  apiGroups: [""]
  verbs:
  - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:update-namespaces-binding
  labels:
    app.kubernetes.io/name: stackrox
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: stackrox:update-namespaces
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:create-events
  labels:
    app.kubernetes.io/name: stackrox
rules:
- resources:
  - events
  apiGroups: [""]
  verbs:
  - create
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:create-events-binding
  labels:
    app.kubernetes.io/name: stackrox
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: stackrox:create-events
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:view-rbac
  labels:
    app.kubernetes.io/name: stackrox
rules:
- resources:
  - roles
  - clusterroles
  - rolebindings
  - clusterrolebindings
  - serviceaccounts
  apiGroups:
  - ""
  - "rbac.authorization.k8s.io"
  verbs:
  - get
  - watch
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:view-rbac-binding
  labels:
    app.kubernetes.io/name: stackrox
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: stackrox:view-rbac
  apiGroup: rbac.authorization.k8s.io
