apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sensor
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
    app: sensor
    auto-upgrade.stackrox.io/component: "sensor"
  annotations:
    owner: stackrox
    email: support@stackrox.com
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: sensor
  template:
    metadata:
      namespace: stackrox
      labels:
        app: sensor
    spec:
      {{if eq .ClusterType "OPENSHIFT_CLUSTER"}}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 25
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/compute
                    operator: In
                    values:
                    - "true"
            - weight: 75
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/infra
                    operator: NotIn
                    values:
                    - "true"
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: NotIn
                    values:
                    - "true"
      {{- end}}
      securityContext:
        runAsUser: 4000
        fsGroup: 4000
      {{if eq .ClusterType "KUBERNETES_CLUSTER"}}
      imagePullSecrets:
        - name: stackrox
      {{- end}}
      serviceAccount: sensor
      containers:
      - image: {{.Image}}
        name: sensor
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /admissioncontroller
            port: 9443
        ports:
          - containerPort: 8443
            name: api
          - containerPort: 9443
            name: webhook
        command:
          - kubernetes-sensor
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
        env:
        {{ range $var, $value := .EnvVars -}}
        - name: {{ $var }}
          value: {{ jsonquote $value }}
        {{ end }}
        - name: {{.PublicEndpointEnv}}
          value: {{.PublicEndpoint}}
        - name: {{.ClusterIDEnv}}
          value: {{.ClusterID}}
        - name: {{.AdvertisedEndpointEnv}}
          value: sensor.stackrox:443
          {{if eq .ClusterType "OPENSHIFT_CLUSTER"}}
        - name: {{.OpenshiftAPIEnv}}
          value: "true"
          {{- end}}
        volumeMounts:
        - name: varlog
          mountPath: /var/log/stackrox/
        - name: sensor-etc-ssl-volume
          mountPath: /etc/ssl/
        - name: sensor-etc-pki-volume
          mountPath: /etc/pki/ca-trust/
        - name: certs
          mountPath: /run/secrets/stackrox.io/certs/
          readOnly: true
        - name: additional-ca-volume
          mountPath: /usr/local/share/ca-certificates/
          readOnly: true
      {{if .MonitoringEndpoint}}
      - name: telegraf
        image: {{.Image}}
        command:
          - /telegraf
        env:
        - name: SERVICE
          value: sensor
        - name: CLUSTER_NAME
          value: {{.ClusterName}}
        - name: PROMETHEUS_ENDPOINT
          value: http://127.0.0.1:9090
        - name: MONITORING_ENDPOINT
          value: {{.MonitoringEndpoint}}
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: varlog
            mountPath: /var/log/stackrox/
          - name: monitoring-client-volume
            mountPath: /run/secrets/stackrox.io/monitoring/certs
            readOnly: true
          - name: telegraf-config-volume
            mountPath: /etc/telegraf/
            readOnly: true
      {{- end}}
      volumes:
      - name: certs
        secret:
          secretName: sensor-tls
          items:
          - key: sensor-cert.pem
            path: cert.pem
          - key: sensor-key.pem
            path: key.pem
          - key: ca.pem
            path: ca.pem
      - name: sensor-etc-ssl-volume
        emptyDir: {}
      - name: sensor-etc-pki-volume
        emptyDir: {}
      - name: additional-ca-volume
        secret:
          secretName: additional-ca-sensor
          optional: true
      - name: varlog
        emptyDir: {}
      {{if .MonitoringEndpoint}}
      - name: monitoring-client-volume
        secret:
          secretName: monitoring-client
      - name: telegraf-config-volume
        configMap:
          name: telegraf
      {{- end}}
---
apiVersion: v1
kind: Service
metadata:
  name: sensor
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
    auto-upgrade.stackrox.io/component: "sensor"
spec:
  ports:
  - name: https
    port: 443
    targetPort: api
    protocol: TCP
  selector:
    app: sensor
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: sensor-webhook
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
    auto-upgrade.stackrox.io/component: "sensor"
spec:
  ports:
  - name: https
    port: 443
    targetPort: webhook
    protocol: TCP
  selector:
    app: sensor
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: stackrox
    service: collector
    app: collector
    auto-upgrade.stackrox.io/component: "sensor"
  name: collector
  namespace: stackrox
spec:
  selector:
    matchLabels:
      service: collector
  template:
    metadata:
      labels:
        service: collector
        app: collector
      namespace: stackrox
    spec:
      {{if .TolerationsEnabled}}
      tolerations:
      - operator: "Exists"
      {{- end}}
      serviceAccount: collector
      containers:
{{if ne .CollectionMethod "NO_COLLECTION"}}
      - name: collector
        image: {{.CollectorImage}}
        imagePullPolicy: Always
        env:
        - name: COLLECTOR_CONFIG
          value: '{"tlsConfig":{"caCertPath":"/var/run/secrets/stackrox.io/certs/ca.pem","clientCertPath":"/var/run/secrets/stackrox.io/certs/cert.pem","clientKeyPath":"/var/run/secrets/stackrox.io/certs/key.pem"}}'
        - name: COLLECTION_METHOD
          value: {{ .CollectionMethod }}
        - name: GRPC_SERVER
          value: "sensor.stackrox:443"
        {{if ne .OfflineMode "true"}}
        - name: MODULE_DOWNLOAD_BASE_URL
          value: {{.CollectorModuleDownloadBaseURL}}
        {{- end}}
        resources:
          limits:
            cpu: 750m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 320Mi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
          privileged: true
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /host/var/run/docker.sock
          name: var-run-docker-sock
        - mountPath: /host/proc
          name: proc-ro
          readOnly: true
        - mountPath: /module
          name: tmpfs-module
        - mountPath: /host/etc
          name: etc-ro
          readOnly: true
        - mountPath: /host/usr/lib
          name: usr-lib-ro
          readOnly: true
        - mountPath: /host/sys
          name: sys-ro
          readOnly: true
        - mountPath: /host/dev
          name: dev-ro
          readOnly: true
        - mountPath: /run/secrets/stackrox.io/certs/
          name: certs
          readOnly: true
{{- end}}
      - command:
        - stackrox/compliance
        env:
        - name: ROX_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: ROX_ADVERTISED_ENDPOINT
          value: sensor.stackrox:443
        image: {{.Image}}
        imagePullPolicy: IfNotPresent
        name: compliance
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/ssl/
          name: etc-ssl
        - mountPath: /etc/pki/ca-trust/
          name: etc-pki-volume
        - mountPath: /host/etc
          name: etc-ro
          readOnly: true
        - mountPath: /host/lib
          name: lib
          readOnly: true
        - mountPath: /host/usr/bin
          name: usr-bin
          readOnly: true
        - mountPath: /host/usr/lib
          name: usr-lib
          readOnly: true
        - mountPath: /host/var/lib
          name: var-lib
          readOnly: true
        - mountPath: /host/var/log/audit
          name: var-log-audit
          readOnly: true
        - mountPath: /host/run
          name: run
        - mountPath: /host/proc
          name: proc-ro
          readOnly: true
        - mountPath: /host/var/run/docker.sock
          name: var-run-docker-sock
        - mountPath: /run/secrets/stackrox.io/certs/
          name: certs
          readOnly: true
      {{if .MonitoringEndpoint}}
      - name: telegraf
        image: {{.Image}}
        command:
          - /telegraf
        env:
        - name: SERVICE
          value: collector
        - name: CLUSTER_NAME
          value: {{.ClusterName}}
        - name: PROMETHEUS_ENDPOINT
          value: http://127.0.0.1:9090
        - name: MONITORING_ENDPOINT
          value: {{.MonitoringEndpoint}}
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        securityContext:
          capabilities:
            drop: ["NET_RAW"]
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: monitoring-client-volume
            mountPath: /run/secrets/stackrox.io/monitoring/certs
            readOnly: true
          - name: telegraf-config-volume
            mountPath: /etc/telegraf/
            readOnly: true
      {{- end}}
      volumes:
      - hostPath:
          path: /var/run/docker.sock
        name: var-run-docker-sock
      - hostPath:
          path: /proc
        name: proc-ro
      - emptyDir:
          medium: Memory
        name: tmpfs-module
      - hostPath: 
          path: /etc
        name: etc-ro
      - hostPath: 
          path: /usr/lib
        name: usr-lib-ro
      - hostPath: 
          path: /sys/
        name: sys-ro
      - hostPath:
          path: /dev
        name: dev-ro
      - name: certs
        secret:
          secretName: collector-tls
          items:
          - key: collector-cert.pem
            path: cert.pem
          - key: collector-key.pem
            path: key.pem
          - key: ca.pem
            path: ca.pem
      - hostPath:
          path: /lib
        name: lib
      - hostPath:
          path: /usr/bin
        name: usr-bin
      - hostPath:
          path: /usr/lib
        name: usr-lib
      - hostPath:
          path: /var/lib
        name: var-lib
      - hostPath:
          path: /var/log/audit
        name: var-log-audit
      - hostPath:
          path: /run
        name: run
      - name: etc-ssl
        emptyDir: {}
      - name: etc-pki-volume
        emptyDir: {}
      {{if .MonitoringEndpoint}}
      - name: monitoring-client-volume
        secret:
          secretName: monitoring-client
      - name: telegraf-config-volume
        configMap:
          name: telegraf
      {{- end}}
