apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockcollector
  namespace: stackrox
  labels:
    app: mockcollector
  annotations:
    owner: stackrox
    email: support@stackrox.com
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mockcollector
  template:
    metadata:
      namespace: stackrox
      labels:
        app: mockcollector
    spec:
      imagePullSecrets:
      - name: stackrox
      containers:
      - image: stackrox/scale:2.2.11.0-41-g157f9e484c
        name: mockcollector
        command:
          - /mockcollector
        volumeMounts:
        - name: varlog
          mountPath: /var/log/stackrox/
        - name: certs
          mountPath: /run/secrets/stackrox.io/certs/
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: collector-tls
          items:
          - key: collector-cert.pem
            path: cert.pem
          - key: collector-key.pem
            path: key.pem
          - key: ca.pem
            path: ca.pem
      - name: varlog
        emptyDir: {}

