apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
- ./tests/central
- ./tests/securedcluster
# central pod takes a while do become healthy, typically ~25s, but sometimes over a minute since container start.
# We need to add CR reconciliation, pod creation and image fetch to that.
# Set the timeout very high so that we can collect a distribution of realistic times and later set to a flake-safe timeout.
timeout: 900
reportFormat: xml
artifactsDir: build/kuttl-test-artifacts
commands:
- command: env NO_PROXY=127.1.2.3/8 ./bin/manager  # use a test value for NO_PROXY. This will not have any impact
                                                   # on the services at runtime, but we can test if it gets piped
                                                   # through correctly.
  background: true
# The following stackrox_namespaces commands are only necessary because we only support a fixed namespace name, which in turn requires
# kuttl --namespace flag, and this in turn requires namespace to be in place before we start testing.
# If/when we support arbitrary namespaces, then we can drop --namespace and the following commands,
# and kuttl will create and clean up ephemeral namespaces for us, with the additional ability to run tests in parallel.
# This first command is a no-op if namespace already exists, but ensures that the second command (delete) does not fail.
- command: kubectl apply -f tests/stackrox_namespaces.yaml
# This is needed to clean up stale resources (PVC, etc) from previous tests, if any.
- command: kubectl delete -f tests/stackrox_namespaces.yaml
# Namespace needs to exist to use kuttl with --namespace
- command: kubectl apply -f tests/stackrox_namespaces.yaml
# Set up operand image pull secrets for development.
- script: |
    set -e # shell in CI does not grok -o pipefail
    secret=$(mktemp)
    ../deploy/common/pull-secret.sh stackrox docker.io > $secret
    kubectl -n stackrox create -f $secret
    rm $secret
parallel: 1  # because we share the namespace :-(
