{{- include "srox.init" . -}}

{{- if ._rox.env._proxyConfig -}}
apiVersion: v1
kind: Secret
metadata:
  name: proxy-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.defaultLabels" . | nindent 4 }}
  annotations:
    {{- include "srox.defaultAnnotations" . | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  config.yaml: |
    {{- ._rox.env._proxyConfig | nindent 4 }}

{{ end }}
