{{- include "srox.init" . -}}

{{ if ._rox.central.defaultTLSCert }}

apiVersion: v1
kind: Secret
metadata:
  name: central-default-tls-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.defaultLabels" . | nindent 4 }}
  annotations:
    {{- include "srox.defaultAnnotations" . | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
type: kubernetes.io/tls
stringData:
  tls.crt: |
    {{- ._rox.central._defaultTLSCert.Cert | nindent 4 }}
  tls.key:
    {{- ._rox.central._defaultTLSCert.Key | nindent 4 }}

{{- end }}
