{{- include "srox.init" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: central-rhsso-client-secret
  namespace: stackrox
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  clientSecret: "secret value"
