{{- include "srox.init" . -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: central
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.defaultLabels" . | nindent 4 }}
  annotations:
    {{- include "srox.defaultAnnotations" . | nindent 4 }}
imagePullSecrets:
{{- range $secretName := ._rox.imagePullSecrets._names }}
- name: {{ quote $secretName }}
{{ end -}}

