{{- include "stackrox.init" . -}}

{{ if ._rox.global.license }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: central-license
  namespace: {{ .Release.Namespace }}
  labels:
    {{ template "defaultLabels" . }}
  annotations:
    {{ template "defaultAnnotations" . }}
    "helm.sh/hook": "pre-install"
stringData:
  license.lic: {{ ._rox.global.license | quote }}
{{ end }}
