{{- include "stackrox.init" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: central-endpoints
  namespace: {{ .Release.Namespace }}
  labels:
    {{ template "defaultLabels" . }}
  annotations:
    {{ template "defaultAnnotations" . }}
    "helm.sh/hook": "pre-install"
data:
  endpoints.yaml:
    {{- ._rox.central.endpoints | toYaml | indent 2 }}
