{{- include "srox.init" . -}}

{{- if not ._rox.scanner.disable -}}

{{- if not (kindIs "invalid" ._rox.scanner._dbPassword.value) -}}

apiVersion: v1
kind: Secret
metadata:
  name: scanner-db-password
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.defaultLabels" . | nindent 4 }}
  annotations:
    {{- include "srox.defaultAnnotations" . | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  password: |
    {{- ._rox.scanner._dbPassword.value | nindent 4 }}

{{- end -}}

{{ end -}}
