apiVersion: v1
data:
  central-config.yaml: |
    {{- .Files.Get "config/central-config.yaml.default" | nindent 4 }}
kind: ConfigMap
metadata:
  name: central-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{ template "defaultLabels" . }}
  annotations:
    {{ template "defaultAnnotations" . }}
