kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox-central-diagnostics
  namespace: {{ .Release.Namespace }}
  labels:
    {{ template "defaultLabels" . }}
  annotations:
    {{ template "defaultAnnotations" . }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stackrox-central-diagnostics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: stackrox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stackrox-central-diagnostics
subjects:
  - kind: ServiceAccount
    name: central
    namespace: {{ .Release.Namespace }}
