apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ext-to-central
  namespace: {{.Release.Namespace}}
  labels:
    {{ template "defaultLabels" . }}
  annotations:
    {{ template "defaultAnnotations" . }}
spec:
  ingress:
  - ports:
    - port: 8443
      protocol: TCP
  podSelector:
    matchLabels:
      app: central
  policyTypes:
  - Ingress
