apiVersion: v1
kind: Secret
metadata:
  namespace: stackrox
  name: proxy-config
  labels:
    {{ template "defaultLabels" . }}
  annotations:
    {{ template "defaultAnnotations" . }}
    "helm.sh/hook": "pre-install"
type: Opaque
stringData:
  config.yaml: {{- .Files.Get "config/proxy-config.yaml.default" | toYaml | indent 2 -}}
