apiVersion: v1
kind: Service
metadata:
  name: central
  namespace: {{.Release.Namespace}}
  labels:
    {{ template "defaultLabels" . }}
  annotations:
    {{ template "defaultAnnotations" . }}
spec:
  ports:
  - name: https
    port: 443
    targetPort: api
  selector:
    app: central
  type: ClusterIP

{{ if .Capabilities.APIVersions.Has "networking.istio.io/v1alpha3/DestinationRule" }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: central-internal-no-istio-mtls
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: stackrox
  annotations:
    stackrox.io/description: "Disable Istio mTLS for port 443, since StackRox services use built-in mTLS."
spec:
  host: central.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: DISABLE
{{ end }}
