{{- include "stackrox.init" . -}}

{{ if ._rox.global.docker.auths }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: stackrox
  namespace: stackrox
  labels:
    {{ template "defaultLabels" . }}
  annotations:
    {{ template "defaultAnnotations" . }}
    "helm.sh/hook": "pre-install"
data:
  .dockerconfigjson: {{ ._rox.global.docker.auths | toJson | b64enc | quote }}
{{ end }}
