{{- include "stackrox.init" . -}}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: central-tls
  namespace: {{.Release.Namespace}}
  labels:
    {{ template "defaultLabels" . }}
  annotations:
    {{ template "defaultAnnotations" . }}
    "helm.sh/hook": "pre-install"
stringData:
  ca.pem: |
    {{- ._rox.global.caCert.Cert | nindent 4 }}
  ca-key.pem: |
    {{- ._rox.global.caCert.Key | nindent 4 }}
  jwt-key.pem: |
    {{- ._rox.central.jwtKey | nindent 4 }}
  cert.pem: |
    {{- ._rox.central.tlsCert.Cert | nindent 4 }}
  key.pem: |
    {{- ._rox.central.tlsCert.Key | nindent 4 }}
