name: Create Test Cluster
on:
  workflow_call:
    secrets:
      INFRA_TOKEN:
        description: Infra access token
        required: true
    inputs:
      flavor:
        description: Flavor (`qa-demo`, `gke-default`, `openshift-4-demo`...)
        type: string
        required: true
      name:
        description: Cluster name
        type: string
        required: true
      lifespan:
        description: Cluster lifespan
        type: string
        default: 48h
        required: false
      args:
        description: Comma separated flavor arguments. Ex. nodes=5,main-image=main:tag
        type: string
        required: false
        default: ""
      wait:
        description: Whether to wait for the cluster readiness
        type: boolean
        required: false
        default: false
      STACKROX_GHA_VERSION:
        description: Sets a version ref for callers in other repos
        type: string
        required: false
        default: ""
    outputs:
      status:
        description: The status of the cluster after this workflow completes
        value: ${{ jobs.infra.outputs.status }}

  workflow_dispatch:
    inputs:
      flavor:
        description: Flavor (`qa-demo`, `gke-default`, `openshift-4-demo`...)
        type: string
        required: true
      name:
        description: Cluster name
        type: string
        required: true
      lifespan:
        description: Cluster lifespan
        type: string
        default: 48h
        required: false
      args:
        description: Comma separated flavor arguments. Ex. nodes=5,main-image=main:tag
        type: string
        required: false
        default: ""
      wait:
        description: Whether to wait for the cluster readiness
        type: boolean
        required: false
        default: false
      STACKROX_GHA_VERSION:
        description: Sets a version ref for callers in other repos
        type: string
        required: false
        default: ""
    outputs:
      status:
        description: The status of the cluster after this workflow completes
        value: ${{ jobs.infra.outputs.status }}

env:
  ACCEPT_RAW: "Accept: application/vnd.github.v3.raw"
  script_url: /repos/${{ github.repository }}/contents/.github/workflows/scripts/common.sh?ref=${{ github.ref_name }}

jobs:
  infra:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.info.outputs.status }}
    steps:
      - name: Download infractl
        run: |
          mkdir -p ~/.local/bin
          curl --fail -sL https://infra.rox.systems/v1/cli/linux/amd64/upgrade \
          | jq -r ".result.fileChunk" \
          | base64 -d \
          > ~/.local/bin/infractl
          chmod +x ~/.local/bin/infractl
          # Ensure that the binary works
          infractl --version

      - name: Create Cluster
        env:
          INFRA_TOKEN: ${{secrets.INFRA_TOKEN}}
          GH_TOKEN: ${{ github.token }}
          GH_NO_UPDATE_NOTIFIER: 1
          STACKROX_GHA_VERSION: ${{ inputs.STACKROX_GHA_VERSION }}
        run: |
          set -uo pipefail
          script_url="${{env.script_url}}"
          if [[ "${{ inputs.STACKROX_GHA_VERSION }}" != "" ]]; then
            script_url="/repos/stackrox/stackrox/contents/.github/workflows/scripts/common.sh?ref=${{ inputs.STACKROX_GHA_VERSION }}"
          fi
          gh api -H "$ACCEPT_RAW" "$script_url" | bash -s -- \
            create-cluster \
            "${{inputs.flavor}}" \
            "${{inputs.name}}" \
            "${{inputs.lifespan}}" \
            "${{inputs.wait}}" \
            "${{inputs.args}}"

      - name: Get Cluster Info
        env:
          INFRA_TOKEN: ${{secrets.INFRA_TOKEN}}
        id: info
        run: |
          name="${{inputs.name}}"
          name="${name//./-}"
          info="$(infractl 2>/dev/null get "$name" --json)"
          echo "Cluster info:"
          echo "$info"
          status="$(echo $name | jq -r '.Status')"
          echo "::set-output name=status::$status"
