name: Prepare Operator Release Branch
on:
  push:
    branches:
      - 'release/*'

jobs:
  prepare_operator_release:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/stackrox
      DRY_RUN: false

    steps:
    - uses: actions/checkout@v1

    - name: Parse repo go version file
      shell: bash
      run: echo "##[set-output name=gover;]$(cat EXPECTED_GO_VERSION | egrep -o '[0-9].*')"
      id: go_ver

    - uses: actions/setup-go@v2
      with:
        go-version: '^${{ steps.go_ver.outputs.gover }}'

    - name: Update Git config in runner
      run: git config --global --add url.git@github.com:.insteadOf https://github.com/
      shell: bash

    - name: Setup SSH key
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        set -eu
        mkdir -p ~/.ssh
        ssh-keyscan github.com >>~/.ssh/known_hosts
        ssh-agent -a "$SSH_AUTH_SOCK" >/dev/null
        ssh-add - <<<"${{ secrets.ROXBOT_SSH_KEY }}"

    - name: Call prepare-rh-release.sh
      run: |
        source_branch="${GITHUB_REF#refs/heads/}"
        target_branch="${source_branch/release\//release-operator/}"
        ./scripts/redhat-infra-release/prepare-rh-release.sh . "${source_branch}" "${target_branch}"
      shell: bash
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
