name: Prepare Operator Release Branch
on:
  push:
    tags:
    - '[1-9][0-9]*.[0-9]+.[0-9]+' # Matches release tags, e.g. 3.62.1
    - '[1-9][0-9]*.[0-9]+.[0-9]+-rc.[0-9]+' # Matches release candidate tags, e.g. 3.62.1-rc.4
    # These tags filters should be in sync with filters in CircleCI, see
    # https://github.com/stackrox/rox/blob/a434dd34a8aad5ce33dac86282c4f02cdb90b7d5/.circleci/config.yml#L6-L22
    # Keep in mind that GitHub filter patterns are not regexes. Info on syntax here:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet


jobs:
  prepare_operator_release:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/stackrox
      DRY_RUN: false

    steps:
    - uses: actions/checkout@v1

    - name: Parse repo go version file
      shell: bash
      run: echo "##[set-output name=gover;]$(cat EXPECTED_GO_VERSION | egrep -o '[0-9].*')"
      id: go_ver

    - uses: actions/setup-go@v2
      with:
        go-version: '^${{ steps.go_ver.outputs.gover }}'

    - name: Update Git config in runner
      run: git config --global --add url.git@github.com:.insteadOf https://github.com/
      shell: bash

    - name: Setup SSH key
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        set -eu
        mkdir -p ~/.ssh
        ssh-keyscan github.com >>~/.ssh/known_hosts
        ssh-agent -a "$SSH_AUTH_SOCK" >/dev/null
        ssh-add - <<<"${{ secrets.ROXBOT_SSH_KEY }}"

    - name: Call prepare-rh-release.sh
      run: |
        source_tag="${GITHUB_REF#refs/tags/}"
        target_tag="operator-${source_tag}"
        target_branch=$(awk -F \. '{printf "release-operator/%s.%s.x", $1, $2}' <<< $source_tag)
        ./scripts/redhat-infra-release/prepare-rh-release.sh . "${source_tag}" "${target_tag}" "${target_branch}"
      shell: bash
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
