# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 0 * * *'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Scan with Trivy
    strategy:
      matrix:
        image:
          - main
          - roxctl
          - central-db
    runs-on: ubuntu-18.04
    steps:
          - name: Run Trivy vulnerability scanner in repo mode
            uses: aquasecurity/trivy-action@master
            with:
              image-ref: 'quay.io/stackrox-io/${{ matrix.image }}:latest'
              scan-type: 'image'
              ignore-unfixed: true
              format: 'sarif'
              output: 'trivy-results.sarif'
              severity: 'CRITICAL'

          - name: Upload Trivy scan results to GitHub Security tab
            uses: github/codeql-action/upload-sarif@v2
            with:
              sarif_file: 'trivy-results.sarif'
              category: ${{ matrix.image }}
