version: "3.2"
services:
  clairify:
    image: {{.SwarmConfig.ClairifyImage}}
    entrypoint:
      - /init
      - /clairify
    environment:
      - CLAIR_ARGS=-insecure-tls
    networks:
      net:
    deploy:
      labels:
        owner: stackrox
        email: support@stackrox.com
      resources:
         reservations:
           cpus: '0.5'
           memory: 500M
         limits:
           cpus: '2.0'
           memory: 2G
networks:
  net:
    driver: overlay
    attachable: true
