version: "3.2"
services:
  sensor:
    image: {{.Image}}
    entrypoint:
      - swarm-sensor
    networks:
      net:
    deploy:
      labels:
        owner: stackrox
        email: support@stackrox.com
{{if eq .DisableSwarmTLS "true" }}
      placement:
        constraints:
          - node.role==manager
{{- end}}
      resources:
        reservations:
          cpus: '0.2'
          memory: 200M
        limits:
          cpus: '0.5'
          memory: 500M
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      - "{{.PublicEndpointEnv}}={{.PublicEndpoint}}"
      - "{{.ClusterIDEnv}}={{.ClusterID}}"
      - "{{.AdvertisedEndpointEnv}}={{.AdvertisedEndpoint}}"
      - "{{.ImageEnv}}={{.Image}}"
{{if ne .DisableSwarmTLS "true" }}
      - "DOCKER_CERT_PATH=/run/secrets/stackrox.io/docker/"
      - "DOCKER_HOST=$DOCKER_HOST"
      - "DOCKER_TLS_VERIFY=$DOCKER_TLS_VERIFY"
{{- end}}
    secrets:
      - source: sensor_certificate
        target: stackrox.io/certs/cert.pem
        mode: 400
      - source: sensor_private_key
        target: stackrox.io/certs/key.pem
        mode: 400
      - source: central_certificate
        target: stackrox.io/certs/ca.pem
        mode: 400
{{if ne .DisableSwarmTLS "true" }}
      - source: docker_client_ca_pem
        target: stackrox.io/docker/ca.pem
        mode: 400
      - source: docker_client_cert_pem
        target: stackrox.io/docker/cert.pem
        mode: 400
      - source: docker_client_key_pem
        target: stackrox.io/docker/key.pem
        mode: 400
{{- end}}
      - source: registry_auth
        target: stackrox.io/registry_auth
        mode: 400
networks:
  net:
    driver: overlay
    attachable: true
secrets:
  sensor_private_key:
    file: sensor-key.pem
  sensor_certificate:
    file: sensor-cert.pem
  central_certificate:
    file: central-ca.pem
{{if ne .DisableSwarmTLS "true"}}
  docker_client_ca_pem:
    file: docker-ca.pem
  docker_client_cert_pem:
    file: docker-cert.pem
  docker_client_key_pem:
    file: docker-key.pem
{{- end}}
  registry_auth:
    file: registry-auth
